### ISSUE TITLE
12.7mm Rotary Cannon

### ISSUE THREAD

**Issue by TheWizardLizard** [nrlulz/ACF#200]
So I was snooping around the ACF Models files and I came across a 12.7mm RAC model, so I was like, "Why don't I use this as my first crack at simple lua coding?" So I did.

ACF_definegun(“12.7mmRAC”, {
name = “12.7mm Rotary Autocannon”,
desc = “The 12.7mm Rotary Cannon, based off of the GAU-19/A, flings .50BMG at rediculous speeds, no remorse.”,
model = “models/rotarycannon/rotarycannon_127mm.mdl”,
gunclass = “RAC”,
caliber =0.50, --does this affect fire rate?? Also based off of the gau-19 caliber
weight =670,
year =1983,
magsize =100, --change as you see fit
magreload =1.3,
round = {
maxlength =15.8,
propweight =0.03,
}
})

Feel free to change any values as you see fit if you decide to add the gun, since they are untested, I recommend you test it. I have no idea if it was scrapped due to balancing issues or something else. 

Round values were based off of the code at "ACF/lua/acf/shared/guns/machinegun.lua" 

Caliber is based off of the real life caliber of .50cal, where in the machinegun.lua its 1.27

The gun is also rather small ingame so the weight might have to be reduced.

Also note I used some other values before this and when I tested the gun ingame with AP it had a Rounds-per-minute of about 6000... considering that the real life RPM is 1000-2000, some other balancing may be needed.

POSTEDIT - Also when testing the gun, the sound was absolutely horrendous. Is there a way to implement something like "RACStart.wav, "RACMid.wav, RACStop.wav" as a way to fix the sounds, because the way I see it is that the gun calls the sound whenever a shell is spawned or the gun fires.

**Comment by Bubbus** [comment]
We had 12.7 RACs a while back but they were removed.  The main argument against them was lag, but now that MGs are parentable we're seeing a lot of clustered MG arrays which output similar volumes of fire and therefore cause similar lag.
Because of that an MG-caliber RAC doesn't have a place in ACF because an MG array will always be more efficient.  However, if a RAC was given an inaccuracy of 0.5 degs or so it could find a niche in aircraft and light vehicles for area fire?

I have the opinion that RACs need to be looked at for rebalance because they're rarely used now.  HMGs are more efficient for all our HE-spam needs.  Maybe they can find a niche with high rate of fire and high calibers but low accuracy and high reload times - but locked to AP to remove HE-spam lag issues.  Just throwing out ideas here.

**Comment by TheWizardLizard** [comment]
Just to ask, what exactly does "rofmod" do? I feel like it relates to the rate of fire of the gun.

**Comment by Bubbus** [comment]
Yeah it's a straight multiplier for the delay between shots.
https://github.com/nrlulz/ACF/blob/c7b578e847f69666cd4ca8eac02eca8b9e443d85/lua/entities/acf_gun.lua#L711

**Comment by Fervidusletum** [comment]
I was testing the viability of 12.7 rac months ago, decided against adding it because, as bubbus mentioned mgs are lighter and parentable, and 12.7 rac is light enough to be massed together in its own right which would massively strain server. They simply are not a viable addition to acf, and unlikely to be added.

**Comment by AnonaMoose21** [comment]
wizard when moose gets bored he makes things for server's or brings coding in from acf that's not in or on request ;)

**Comment by deathking61** [comment]
hey just a question im using ACF to play around on a lan server (so i can not have lag on holos) but i wanna know how i can add propellant not a lot more just more and not have the gun jerk to hard when its shot any ideas?

**Comment by TheWizardLizard** [comment]
lol why are you even using this code the values are all wrong.
